### ISSUE TITLE
Add fallback for `posix_memalign`

### ISSUE THREAD

**Issue by barracuda156** [Drup/ocaml-lmdb#50]
Current code fails to compile on macOS 10.5.8 due to missing `posix_memalign`:
```
:notice:build --->  Building ocaml-dune
:debug:build Executing org.macports.build (ocaml-dune)
:debug:build Environment: 
:debug:build CC_PRINT_OPTIONS='YES'
:debug:build CC_PRINT_OPTIONS_FILE='/opt/local/var/macports/build/ocaml-dune-5e8b4aac/work/.CC_PRINT_OPTIONS'
:debug:build CPATH='/opt/local/include'
:debug:build DEVELOPER_DIR='/Developer'
:debug:build LIBRARY_PATH='/opt/local/lib'
:debug:build MACOSX_DEPLOYMENT_TARGET='10.5'
:debug:build MACPORTS_LEGACY_SUPPORT_DISABLED='1'
:debug:build SOURCE_DATE_EPOCH='1772729228'
:info:build Executing:  cd "/opt/local/var/macports/build/ocaml-dune-5e8b4aac/work/dune-3.21.1" && DUNE_CONFIG__COPY_FILE=portable /usr/bin/make release 
:debug:build system:  cd "/opt/local/var/macports/build/ocaml-dune-5e8b4aac/work/dune-3.21.1" && DUNE_CONFIG__COPY_FILE=portable /usr/bin/make release 
:info:build ocamlc -output-complete-exe -intf-suffix .dummy -g -o .duneboot.exe -I boot unix.cma boot/types.ml boot/libs.ml boot/duneboot.ml
:info:build ./.duneboot.exe
:info:build cd _boot && /opt/local/bin/ocamlc -c -g -I +threads mdb.c
:info:build vendor/ocaml-lmdb/mdb.c: In function 'mdb_env_copyfd1':
:info:build vendor/ocaml-lmdb/mdb.c:10515:13: error: implicit declaration of function 'posix_memalign' [-Wimplicit-function-declaration]
:info:build vendor/ocaml-lmdb/mdb.c:10515:35: warning: 'posix_memalign' argument 2 type is 'unsigned int' where 'long unsigned int' is expected in a call to built-in function declared without prototype [-Wbuiltin-declaration-mismatch]
:info:build <built-in>: note: built-in 'posix_memalign' declared here
:info:build vendor/ocaml-lmdb/mdb.c:10193:18: warning: 'posix_memalign' argument 3 type is 'int' where 'long unsigned int' is expected in a call to built-in function declared without prototype [-Wbuiltin-declaration-mismatch]
:info:build vendor/ocaml-lmdb/mdb.c:10515:50: note: in expansion of macro 'MDB_WBUF'
:info:build <built-in>: note: built-in 'posix_memalign' declared here
:info:build make: *** [_boot/dune.exe] Error 2
:info:build Command failed:  cd "/opt/local/var/macports/build/ocaml-dune-5e8b4aac/work/dune-3.21.1" && DUNE_CONFIG__COPY_FILE=portable /usr/bin/make release 
:info:build Exit code: 2
```
MacOS would be just as happy with a simple `malloc`.

**Comment by madroach** [comment]
I don't have access to a macOS machine.

The problem seems to be compilation of the shipped lmdb backend library.

Would you be so kind and try to build lmdb on your machine?
It should be as easy as `make -C liblmdb/libraries/liblmdb` from the root of the ocaml-lmdb source.
If this fails, too, there is a bug in the lmdb backend. If this builds fine, I have to look into the build scripts and whether I need to add some CFLAGS.

**Comment by madroach** [comment]
Ping? Are you able to build the liblmdb backend. Can I help you with trying to build it on macOS?

**Comment by barracuda156** [comment]
@madroach I apologize, I missed the notification earlier, and this went forgotten. I am out of station at the moment and will be back to my hardware in about two weeks. I make a reminder for myself to address this once I am back.
